/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.graphics.drawable.animated;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int coordinatorLayoutStyle = 0x7f03007e;
        public static final int font = 0x7f0300a7;
        public static final int fontProviderAuthority = 0x7f0300a9;
        public static final int fontProviderCerts = 0x7f0300aa;
        public static final int fontProviderFetchStrategy = 0x7f0300ab;
        public static final int fontProviderFetchTimeout = 0x7f0300ac;
        public static final int fontProviderPackage = 0x7f0300ad;
        public static final int fontProviderQuery = 0x7f0300ae;
        public static final int fontStyle = 0x7f0300af;
        public static final int fontWeight = 0x7f0300b0;
        public static final int keylines = 0x7f0300cc;
        public static final int layout_anchor = 0x7f0300cf;
        public static final int layout_anchorGravity = 0x7f0300d0;
        public static final int layout_behavior = 0x7f0300d1;
        public static final int layout_dodgeInsetEdges = 0x7f0300fd;
        public static final int layout_insetEdge = 0x7f030106;
        public static final int layout_keyline = 0x7f030107;
        public static final int statusBarBackground = 0x7f030155;
    }
    public static final class bool {
        private bool() {}

        public static final int abc_action_bar_embed_tabs = 0x7f040000;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050058;
        public static final int notification_icon_bg_color = 0x7f050059;
        public static final int ripple_material_light = 0x7f050064;
        public static final int secondary_text_default_material_light = 0x7f050066;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f060050;
        public static final int compat_button_ins